//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LekhaCommerceClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubjectMaster
    {
        public int Id { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> SubCourseId { get; set; }
        public string SubjectName { get; set; }
        public string SubjectDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tbl_CourseManagment tbl_CourseManagment { get; set; }
        public virtual tbl_subCourses tbl_subCourses { get; set; }
    }
}
